import type { Metadata } from "next";
import { Autour_One, Geist, Geist_Mono, Jost } from "next/font/google";
import "./globals.css";
import { NavBar } from "./components/layout/NavBar";
import { Footer } from "./components/layout/Footer";
import { Shell } from "./components/Shell";

const autour = Autour_One({
  variable: "--font-autour",
  subsets: ["latin"],
  weight: "400",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${autour.variable} ${geistMono.variable} h-full antialiased dark`}
    >
      {/* <NavBar /> */}
      <body className="min-h-full flex flex-col bg-slate-950 text-slate-100">
        {children}
      </body>
      {/* <Footer /> */}
    </html>
  );
}
